### ISSUE TITLE
0.5.3 Session middleware breaks app

### ISSUE THREAD

**Issue by ilanbiala** [kcbanner/connect-mongo#146]
After updating to 0.5.3, this code breaks my app and nothing after this middleware gets run.

```
app.use(session({
    saveUninitialized: true,
    resave: true,
    secret: config.sessionSecret,
    store: new MongoStore({
      mongooseConnection: db.connection,
      collection: config.sessionCollection
    })
  }));
```

where `db.connection` is a result of `mongoose.connect()` and `config.sessionCollection` is a string.

**Comment by jdesboeufs** [comment]
`mongoose.connect()` return a `Mongoose` instance and not a `Connection` instance.

You must choose between __basic usage__ and __advanced usage__ in our Readme, but not mix them.

**Comment by ilanbiala** [comment]
Db is a mongoose instance, isn't db.connection the connection.

**Comment by jdesboeufs** [comment]
I need more informations.

**Comment by ilanbiala** [comment]
@jdesboeufs sorry I'm not using the advanced, I'm working off of the "Reuse a mongoose connection - basic usage"

In the Node REPL, I checked that `mongoose.connection === db.connection` where `db = mongoose.connect()`. So what could be wrong?

**Comment by jdesboeufs** [comment]
What do you mean when you say that?
> this code breaks my app and nothing after this middleware gets run

**Comment by ilanbiala** [comment]
The app doesn't go past that line. I placed two middlewares, one before and one after, to see where it gets stuck, and only the first gets called. I can wait for 10 minutes and nothing will happen.

**Comment by jdesboeufs** [comment]
The middleware is waiting for the connection...
Maybe there is an error to catch.

**Comment by ilanbiala** [comment]
the `db` is already defined there, because the session code runs in a promise that is resolved by `mongoose.connect()`.

**Comment by jdesboeufs** [comment]
Can you submit a test which reproduce your problem?

**Comment by ilanbiala** [comment]
A minimal reproduction scenario or an actual test?

**Comment by jdesboeufs** [comment]
As you want.
You describe a very basic usage, exactly the same I use in production, so I'm a bit confused.

**Comment by ilanbiala** [comment]
```
var db = mongoose.connect(config.db, function(err) {
  if (!err) {
    var session = require('express-session');
    var MongoStore = require('connect-mongo')(session);
    
    // stops right here
    app.use(session({
      saveUninitialized: true,
      resave: true,
      secret: 'abc',
      store: new MongoStore({
        mongooseConnection: db.connection,
        collection: 'sessions'
      })
    }));
  }
});
```
There are some promises that wrap around this and go through different files, but I have `console.log()`ed to find where it stops, and it stops right when I use the session.

**Comment by jdesboeufs** [comment]
Your code is complicated.
`connect-mongo` is natively able to wait for the connection.

But if you still want to keep this logic, just replace `db.connection` by `mongoose.connection`.
Your `db` variable must equal to `undefined`.

**Comment by ilanbiala** [comment]
`db.connection` produces the same as `mongoose.connection`, so how can `db === undefined`? Also, waiting for the connection adds time and complexity, doesn't it? I can just give it the connection if I have it already..

**Comment by jdesboeufs** [comment]
Can you `console.log()` the value of `db.connection.readyState`, inside your callback?

**Comment by ilanbiala** [comment]
`db.connection.readyState` = 1 right before I use the session middleware and ask connect-mongo to connect.

**Comment by jdesboeufs** [comment]
I'm not able to reproduce your problem.
Can you write a regular test or submit a small codebase in a GitHub repo?

**Comment by ilanbiala** [comment]
@jdesboeufs what changes were made between 0.5.2 and 0.5.3?
