### ISSUE TITLE
Road to 1.0

### ISSUE THREAD

**Issue by jdesboeufs** [kcbanner/connect-mongo#147]
Hi everybody.

I'm opening this issue to track potential upcoming features.
Contributions are welcomed ;)

* [x] Support upcoming Express 5.0 
* [x] Support upcoming native MongoDB driver 2.0 (since `0.5.0`)
* [x] Support upcoming Mongoose 4.0 (since `0.5.0`)
* [x] <del>Support Node.js 0.11 (since `0.5.0`)</del>
* [x] Support io.js (since `0.5.0`)
* [x] Support Node.js 0.12 (since `0.5.0`)
* [ ] Clean API
* [ ] Add timeout to initialization
* [ ] Improve error management
* [x] Improve sessions TTL (since `0.6.0`)
* [ ] Improve tests
* [ ] Clean code

**Comment by ilanbiala** [comment]
@jdesboeufs 4.0.0-rc1 was just released a couple days ago, so it looks like we can start testing support for Mongoose 4.0 soon. :)

**Comment by jdesboeufs** [comment]
4.0.0-rc1 is supported ;)
I've updated all the things.

**Comment by ilanbiala** [comment]
@jdesboeufs what does cleaning the API entail?
