### ISSUE TITLE
How does connect-mongo handle db failure?

### ISSUE THREAD

**Issue by a00andos** [kcbanner/connect-mongo#148]
How does connect-mongo handle db failure?
Q1: What if the mongo server is offline when starting the app?
Q2: What if the mongo server connection is disrupted during runtime?

**Comment by jdesboeufs** [comment]
If you don't rely on mongoose, `connect-mongo` will throw an exception which may crash your app.
If the server connection is disrupted and `autoReconnect` is `true`, try again!
Otherwise you have a problem :D

I'll fix this _issue_ as soon as possible.

**Comment by a00andos** [comment]
Thanks for your answer, but I require some clarifications =)
I'm using Mongo Native 2.0.6. Server `autoReconnect` is `true` as default, and thats what I'm using. 
So the answer are as follows? 
**Q1:** An exception is thrown, which may crash my app... Should I `catch` this exception in order not to crash? And in that case, where?
**Q2:** The connection will try to auto reconnect if connection is disrupted... So this means that request that rely on connect-mongo will be stuck in loading until db is running again? Is there a way for me to tell connect-mongo to return an error page if the connection is down?.

And some more questions:
**Q3:** *-"Otherwise you have a problem"*... I'm not sure what *otherwise* are refering to here=D

**Q4** What exactly is the *issue* you are going to fix ? =)

Thanks again for your help and module!

**Comment by ilanbiala** [comment]
@jdesboeufs I'm also curious as to what issue can be fixed in connect-mongo.

**Comment by cvillemure** [comment]
I would like to have an "autoReconnect" timeout to be able to send an error message to the client instead of being stuck in an infinite loop!

**Comment by quilesbaker** [comment]
@marcoslhc and me forked and added the error emitter. @jdesboeufs: Will probably submit a pull request soon for this issue.

**Comment by quilesbaker** [comment]
@kcbanner ^

**Comment by jdesboeufs** [comment]
Yes!

**Comment by quilesbaker** [comment]
Need to make tests pass first.

**Comment by mfmendiola** [comment]
@quilesbaker Thanks for this fix!  Any idea when this will be released?

**Comment by jdesboeufs** [comment]
Since v1.0.0 is upcoming, I close this issue.
Feel free to create a new one if the problem stay.
