### ISSUE TITLE
Implementation of .touch() interface

### ISSUE THREAD

**Issue by rafaelcardoso** [kcbanner/connect-mongo#149]
There are plans to implement Session.touch() interface?
I'm really enjoying this middleware but I need to use this feature.

Reference:

https://github.com/expressjs/session#sessiontouch
https://github.com/expressjs/session/commit/b5e63324ed83c1c1401029e9ad2a97bf9f052c2c

**Comment by jdesboeufs** [comment]
The feature is already implemented!
Le mer. 21 janv. 2015 à 18:43, Rafael Cardoso <notifications@github.com> a
écrit :

**Comment by rafaelcardoso** [comment]
Then, I guess i'm doing something wrong...

I'm using connect-mongo 0.6.0, express 4.11.1, and express-session 1.10.1

I just checked express-session code where it verify if the store module (connect-mongo) has the touch method implemented (on this line https://github.com/expressjs/session/blob/master/index.js#L132 )

And this test is returning false for me.. Any Ideas?

Thank you..

**Comment by rafaelcardoso** [comment]
Here is my config:

app.use(session({
	secret: configAuth.sessionSecret,
 	cookie: {
 		maxAge: configAuth.cookieLifeTime
 	},
	saveUninitialized: false,
	resave: false,
	rolling: false,
	store: new mongoStore({
		collection: 'guaxinim_session',
		mongooseConnection: mongoose.connection,
		autoRemove: 'interval',
		autoRemoveInterval: 20, // In minutes
		hash: {
			salt: configAuth.sidSaltSecret,
			algorithm: 'sha1'
		}
	})
}));

When I try to do this:

router.get('/', function(req, res) {
	req.session.touch();
  	res.render('index', {
  		partials: ['partials/main']
  	});
});

Nothing happens on database :/

**Comment by jdesboeufs** [comment]
The feature you describe, `session.touch()`, already work if `resave: true`.

But yes, `express-session` 1.10.1 introduces a new API `store.touch()`, to force touching even if `resave` is set to `false`.

So let's go ;)

**Comment by jdesboeufs** [comment]
I can't add tests and release today.
Have fun with `master` branch :)
