### ISSUE TITLE
Problem using Mongoose.createConnection

### ISSUE THREAD

**Issue by minmur** [kcbanner/connect-mongo#153]
Hi.

Maybe the problem is somewhere else, but my modest knowledge of node, express, etc. "points" to this package. 

I have one middleware:
```javascript
app.use(function(req, res, next){
  var db = mongoose.createConnection('localhost/uvs-dev');
  app.set('dbConnection', db);
  
  db.on('connected', function () {
    console.log('Mongoose connection opened');
  });

  db.on('error', console.error.bind(console, 'connection error:'));

  next();
});
```

And it works as expected. At least, i get 'Mongoose connection opened' message.

Next middleware uses connect-mongo:
```javascript
app.use(
    session({
      secret: config.secrets.session,
      resave: true,
      saveUninitialized: true,
      store: new mongoStore({ mongoose_connection: app.get('dbConnection') })
    }));
```

But i get an error: `Required MongoStore option "db" missing`

I'm using https://github.com/DaftMonk/generator-angular-fullstack. Maybe it has some gotcha. Any help would be very appreciated.

**Comment by jdesboeufs** [comment]
Your first middleware is useless since `connect-mongo` already wait for connection.
And above all, it is badly designed.

When you declare a middleware, it will be used on each request. But when you call `session()` which effectively returns a middleware, the content of your first middleware has not been called yet.

**Comment by minmur** [comment]
Thanks, understood why this error occurs.

What i want to do is to connect do different database depending on subdomain, i.e. each of my customer will have it's own database. So i guess i need middleware which will be used on every request to detect which db to use.
Code i wrote here is very simplified and just for testing and trying to understand how things work.

**Comment by jdesboeufs** [comment]
Each `connect-mongo` deals with one db connection.
I think you should try another design, or another tool.

**Comment by minmur** [comment]
Thanks for info
