### ISSUE TITLE
Node.js 0.8 support

### ISSUE THREAD

**Issue by jdesboeufs** [kcbanner/connect-mongo#157]
Hi,

connect-mongo `1.0` will drop Node.js `0.8` support.
We will take care that all the roadmap (#147) will be implemented in the `0.x` branch.

Any objection?

**Comment by ilanbiala** [comment]
@jdesboeufs is there anything that requires 0.10? I'm fine with dropping test support for it, but we shouldn't try to break compatibility, should we?

**Comment by jdesboeufs** [comment]
Dropping test support = Dropping support
Be sure I will not break compatibility for my pleasure :)

**Comment by ilanbiala** [comment]
Is there any reason to actually not have code tested against it? It's free and it doesn't fail on 0.8 right?
