### ISSUE TITLE
Error with session

### ISSUE THREAD

**Issue by thedug** [kcbanner/connect-mongo#159]
This error just popped up in my dev environment. Not really sure what is going on here.

auth_1   | Error: Error getting collection: sessions
auth_1   |     at node_modules/connect-mongo/lib/connect-mongo.js:163:19
auth_1   |     at Db.collection (/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:501:27)

I added logging to connect-mongo and this seems to be the underling exception
auth_1   | [TypeError: Cannot read property 'hasListIndexesCommand' of undefined]

I poked around a bit and the only related thing I've seen is super old.

**Comment by jdesboeufs** [comment]
Can you give us some details? (MongoDB version, configuration, mongoose version, driver version, Node.js version...)
