### ISSUE TITLE
Sessions don't seem to be deleted

### ISSUE THREAD

**Issue by ilanbiala** [kcbanner/connect-mongo#160]
I think sessions keep being created and some of my sessions aren't even being deleted it seems. Should I be setting a property or are they deleted automatically after a certain period of time?

**Comment by ilanbiala** [comment]
@jdesboeufs any idea what I'm doing wrong?

**Comment by jdesboeufs** [comment]
https://github.com/kcbanner/connect-mongo#remove-expired-sessions
You have the choice!

**Comment by ilanbiala** [comment]
@jdesboeufs I'm just using the default with 2.6, but my sessions keep building up.

**Comment by jdesboeufs** [comment]
I need more informations: options used, versions...

**Comment by ilanbiala** [comment]
connect-mongo ~0.7.0, options:
```
app.use(session({
    saveUninitialized: true,
    resave: false,
    secret: config.sessionSecret,
    store: new MongoStore({
      mongooseConnection: db.connection,
      collection: config.sessionCollection
    })
  }));
```

**Comment by jdesboeufs** [comment]
Can you check if the TTL index has been set?
If yes, you have a problem with MongoDB.

**Comment by ilanbiala** [comment]
How do I check?

**Comment by jdesboeufs** [comment]
$ mongo
> use yourDb
> db.sessions.getIndexes()

And copy/paste the result!

**Comment by apitts** [comment]
@ilanbiala did you ever get to the bottom of this? I'm assuming you are using mean.js (like I am)...I'm having the same issue with similar code. 

Here is the output of db.sessions.getIndexes( ):
```
[
	{
		"v" : 1,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "myDb.sessions"
	},
	{
		"v" : 1,
		"key" : {
			"expires" : 1
		},
		"name" : "expires_1",
		"ns" : "myDb.sessions",
		"expireAfterSeconds" : 0
	}
]

```
