### ISSUE TITLE
Problem with connecting mongodb driver 2.0.x

### ISSUE THREAD

**Issue by barisusakli** [kcbanner/connect-mongo#161]
Mongodb 3.0
node-mongodb-native 2.0.19
connect-mongo 0.7.0

When I run a query on the database it never calls the callback. If I remove the connect mongo init code it works fine. Here is the relevant code.

```
var session = require('express-session'),
var sessionStore = require('connect-mongo')(session);

mongoClient.connect(connString, connOptions, function(err, _db) {

    // if the below 3 lines are commented out the findOne query works properly
    module.sessionStore = new sessionStore({
       db: _db
    });
    
   _db.collection.findOne({_key:"someKey"}, {}, function(err, data) {
         console.log('never reaches here');
    });
});
```

**Comment by barisusakli** [comment]
Seems like `options.db.openCalled` is undefined no matter what. If I set it to true before I create the session store the queries work.

**Comment by jdesboeufs** [comment]
Most of the connection strategies are not tested yet :(
I think the problem is related to `node-mongodb-native` 2.0.

**Comment by franckl** [comment]
I have a similar issue, I upgraded to mongodb native 2.0.21 from 1.4.32 and it stopped working. My code is the same as @barisusakli

**Comment by barisusakli** [comment]
As temp work around this works for me 

```
mongoClient.connect(connString, connOptions, function(err, db) {
    db.openCalled = true
    module.sessionStore = new sessionStore({
       db: db
    });
    //rest of code
```

**Comment by jdesboeufs** [comment]
I'm on it.

**Comment by 1999** [comment]
Just in case anyone faced with a problem when express is likely not giving a response for a long time - the trick is to switch to mongodb@2.0.x (npm package). It seems like MongoClient.connect had actually connected to MongoDB before 2.x, and this behaviour changed now.

**Comment by 1999** [comment]
@barisusakli oh does it? I have this king of log:
```
  connect-mongo switched to state: init +0ms
  connect-mongo use strategy: `native_db` +1ms
conn ready
  connect-mongo switched to state: connected +0ms
  connect-mongo switched to state: connecting +0ms
```

**Comment by 1999** [comment]
Made a little fix in #165

**Comment by mjmasn** [comment]
I'm passing an existing Db instance to connect-mongo. The fix in #165 doesn't work for me, I still have to set ```db.openCalled = true``` (but only for external database hosted on compose, a database running on localhost works fine)

**Comment by jdesboeufs** [comment]
How can we detect the state of this existing Db instance in mongodb driver 2.0?

**Comment by 1999** [comment]
> I still have to set db.openCalled = true (but only for external database hosted on compose, a database running on localhost works fine)

yep, same thing.

> How can we detect the state of this existing Db instance in mongodb driver 2.0?

It seems like "fullsetup" event can be used for that, I'll try to have a look

**Comment by 1999** [comment]
1.4 has openCalled property set to true when open() has been called:
https://github.com/mongodb/node-mongodb-native/blob/02bf8ece1227b0c35448fe16f5d0073de26106a7/lib/mongodb/db.js#L266

2.0 doesn't have this property at all:
https://github.com/mongodb/node-mongodb-native/blob/2771d2a34527a0783fbfc7bda0b7a5604f10c30a/lib/db.js#L188-L202

topology can be one of [Server](http://mongodb.github.io/node-mongodb-native/2.0/api/Server.html) | [ReplSet](http://mongodb.github.io/node-mongodb-native/2.0/api/ReplSet.html) | [Mongos](http://mongodb.github.io/node-mongodb-native/2.0/api/Mongos.html).
Db expores only these events: https://github.com/mongodb/node-mongodb-native/blob/2771d2a34527a0783fbfc7bda0b7a5604f10c30a/lib/db.js#L163-L170

Server's event to listen to is 'connect': http://mongodb.github.io/node-mongodb-native/2.0/api/Server.html#event:connect
ReplSet's event is 'open': http://mongodb.github.io/node-mongodb-native/2.0/api/ReplSet.html#event:open
Mongos' is also 'open': http://mongodb.github.io/node-mongodb-native/2.0/api/Mongos.html#event:open

Two problems here are:
1) open event is not mentioned in docs: http://mongodb.github.io/node-mongodb-native/2.0/api/Db.html
2) Server's 'connect' event is not fired by Db

**Comment by chapati** [comment]
Huh, I killed the whole day for this issue. Why not mention in docs? Your 5 minutes will save time for people.

**Comment by 1999** [comment]
@chapati did v0.8.1 help you or not?

**Comment by chapati** [comment]
@1999 Haven't checked yet. Figured out the same workaround with openCalled = true as suggested above. Will try v0.8.1 soon.
