### ISSUE TITLE
Error:Required MongoStore option `db` missing

### ISSUE THREAD

**Issue by EdwardStudy** [kcbanner/connect-mongo#164]
It's run successfully at ~0.4.1.
But When I update to 0.7.0, The error is coming.

The database config is</br>
```
var db = mongoose.connect(config.db);
```

The express config is</br>
```
var mongoStore = new MongoStore({
    db: db.connection.db
});
app.use(session({
    saveUninitialized: true,
    resave: true,
    secret: config.sessionSecret,
    store: mongoStore
}));
```

And I console.log the `db.connection.db`, That is a object like this:</br>
![db.connection.db](http://edwardsblog.qiniudn.com/image/1/2f/8fb23dcd48d1ce6c1da04bb8a6a13.png)

Thank you for your attention.

**Comment by jdesboeufs** [comment]
You should use this:
```js
var mongoStore = new MongoStore({
    mongooseConnection: mongoose.connection
});
```
