### ISSUE TITLE
MemoryStore warning

### ISSUE THREAD

**Issue by efkan** [kcbanner/connect-mongo#168]
Hello,

When I use my application as Product I get the following warning message;

> Warning: connect.session() MemoryStore is not designed for a production environment, as it will leak memory, and will not scale past a single process.

I don't know what should I do?

**Comment by ilanbiala** [comment]
Use a more permanent store such as MongoDB.

**Comment by efkan** [comment]
Thanks @ilanbiala ,
I'm already using MongoDB to store session or everything.
What else?

**Comment by ilanbiala** [comment]
Provide your options please (all the time).

**Comment by efkan** [comment]
I don't know why but now there is no *warning* message.Thanks for now :)

**Comment by jdesboeufs** [comment]
This warning is not related to connect-mongo but to express-session or early version of connect.
So I close this issue :)
