### ISSUE TITLE
Last byte of HTTP traffic never sends, connection never closes

### ISSUE THREAD

**Issue by Strat-** [kcbanner/connect-mongo#171]
I... actually don't know how to explain this. I don't know whether to put this issue in express-session or connect-mongo, because I seriously don't know what is causing the issue. I debugged and I debugged, but nothing useful showed up.

Basically, when I have this code:

*express.js*

![](http://puu.sh/hC8RH/7bc9231879.png)

*express-sessions.js*

![](http://puu.sh/hC8Sg/61fd29c362.png)

and the store isn't available because mongoose.connection points to nothing (because it isn't connected), after rendering of this [simple template](http://puu.sh/hC8Wg/f1af6b2bd0.png), it sends everything except the very last byte of the request, while just hanging there. It never sends the last byte. This is what the CURL request looks like:

*with a not-yet-connected connect-mongo session store*

![](http://puu.sh/hC91l/c5ee497186.png)

*without the mongo store (default memory store)* ***OR*** *with a successful mongoose connection*

![](http://puu.sh/hC934/22ffce2625.png)

---

I'm honestly baffled by this. I truly don't know what is causing this, connect-mongo, express-session, or express itself, but it never sends that last byte (and doesn't close the connection either) when I have the store set up (with that bad reference to a connection). Nothing shows up in the debug logs, no exceptions get thrown, literally nothing in the console happens.

I'd appreciate it if I knew what was going on with it.

**Comment by jdesboeufs** [comment]
Did you find a solution?

**Comment by Strat-** [comment]
No. The only way to make it work is to have `MongoStore` actually point to something.

**Comment by jdesboeufs** [comment]
Probably an uncaught exception somewhere...
Did you call `mongoose.connect()` before padding `mongoose.connection`?

**Comment by Strat-** [comment]
I don't remember, likely not.

**Comment by behcet-li** [comment]
I guess express session tries to write the session information to DB and fails. There was an issue with the previous version of connect-mongo where callbacks getting invoked twice - once with error and once with no errors. That probably was breaking express.

Can you try to recreate this after upgrading to the latest version of connect-mongo ?

**Comment by Strat-** [comment]
Sure, but it might take me a while; I got a few things to do beforehand.

**Comment by jdesboeufs** [comment]
You should test with upcoming v1.0.0, on master branch.
I'm ready to re-open the issue if the problem occur again.
