### ISSUE TITLE
How can I get all sessions in mongodb?

### ISSUE THREAD

**Issue by hoozi** [kcbanner/connect-mongo#180]
I get sessions like this `mongoose.model('session');` and `session.find(......)`;but it's wrong~
error message: 
>MissingSchemaError: Schema hasn't been registered for model "session".

How can I do?

**Comment by jdesboeufs** [comment]
`connect-mongo` doesn't use mongoose abstraction layer.
But you can try something like this:
```js
mongoose.connection.db.collection('sessions').find(...)
```

**Comment by Buntelrus** [comment]
node.js MongoDB api doc http://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#find
