### ISSUE TITLE
Session _id

### ISSUE THREAD

**Issue by joetm** [kcbanner/connect-mongo#184]
I save the sessions with `req.session.save()` in my node/express application.
When I look at the session documents stored in MongoDB by connect-mongo, I see that the _id of these documents is a simple string.
It might look like this:
`{
    "_id" : "5ac1f84d-8515-4d71-9f10-5a995b4dd030",
    //...other stuff
}`

Other documents that I save with mongoose get an ObjectId as _id, e.g. `ObjectId("55901d7a8b5f0d32e72453e6")`.

Is that intended? Should the IDs be strings? Or is something misconfigured?

**Comment by jdesboeufs** [comment]
Yes it is intended since the session id is initially created by `express-session`, which is independent from MongoDB.
This session id can also be hashed by `connect-mongo` (optional), so there is no way to turn back to an ObjectId, which is more predictable.

**Comment by dataclear** [comment]
For anyone stumbling upon this issue getting a conversion error on `_id` when accessing the session collection via a model you need to define the `_id` field as a string in your model or mongoose will default it to an `ObjectId`:

```
const sessionSchema = new Schema({
    _id: {
        type: String,
        required: true
    },
    expires: Date,
    session: String
});
```
