### ISSUE TITLE
multiple session object is created. 

### ISSUE THREAD

**Issue by pravin-mindstix** [kcbanner/connect-mongo#191]
Hi, i am using connect-mongo for session handling in my app.

here is my code : 
app.use(session({
      cookie: { maxAge: 1000 * 60 * 60 * 24,  path : '/userprofile/user_Profile'} ,

      secret: "XXXX" ,
      store:new MongoStore({
              db: config.db.name,
              mongooseConnection:mongoose.connection, 
              collection: 'session', 
              stringify:false,
              autoReconnect:true,
              touchAfter: 24 * 3600 // time period in seconds
      }),
      saveUninitialized: true,
      resave: true
  },function(err){
    console.log(err || 'connect-mongodb setup ok');
  }));

problem is that when app hit endpoint --> ( path : '/userprofile/user_Profile'  )  then its creates session object every time. i don't want to create session every time.

in this endpoint what i did is, first I validated session object in this session collection and if object is not present then i want to create new session for user.

request.session.name="userId"

{ "_id" : "wunv7rlnMcU3fz8ocfZWZKL0IBU09TLs", "session" : { "cookie" : { "originalMaxAge" : 86399999, "expires" : ISODate("2015-07-24T09:55:12.052Z"), "secure" : null, "httpOnly" : true, "domain" : null, "path" : "/userprofile/user_Profile" }, "name" : "XX385XXX",  }, "expires" : ISODate("2015-07-24T09:55:12.052Z"), "lastModified" : ISODate("2015-07-23T09:55:12.054Z") }

this is my valid object.

here is empty session object is created  on every call

{ "_id" : "E5uyuBN0mwVfkbMcgSKmKwT3FLNICl1W", "session" : { "cookie" : { "originalMaxAge" : 86400000, "expires" : ISODate("2015-07-24T09:55:21.392Z"), "secure" : null, "httpOnly" : true, "domain" : null, "path" : "/userprofile/user_Profile" } }, "expires" : ISODate("2015-07-24T09:55:21.392Z"), "lastModified" : ISODate("2015-07-23T09:55:21.393Z") }

{ "_id" : "vcwnba_yGUf-CuE-wj8AWTrUIfx6Rmz_", "session" : { "cookie" : { "originalMaxAge" : 86400000, "expires" : ISODate("2015-07-24T10:10:30.636Z"), "secure" : null, "httpOnly" : true, "domain" : null, "path" : "/userprofile/user_Profiler" } }, "expires" : ISODate("2015-07-24T10:10:30.636Z"), "lastModified" : ISODate("2015-07-23T10:10:30.637Z") }

I don't understand what's wrong with this ? 
Thanks for any help.

**Comment by jdesboeufs** [comment]
Hi,

Your problem concern `express-session` above all.
`connect-mongo` is completely unable to create a new session id.

Try to set `saveUninitialized` to `false`.

In your use case you should also remove `db`, `autoReconnect` and `touchAfter` options.

**Comment by pravin-mindstix** [comment]
Thanks for quick response,
 I have removed db, autoReconnect and touchAfter options also set saveUninitialized to false, but still its create records on every request.

**Comment by jdesboeufs** [comment]
Ok.
Try to submit your problem [here](https://github.com/expressjs/session) and please reference this issue ;)

**Comment by pravin-mindstix** [comment]
Oh.. Ok

**Comment by behcet-li** [comment]
I think you are not storing/parsing cookies correctly, so it attempts to create a new session every time.

**Comment by bonesoul** [comment]
@pravin-mindstix what was the cause of the issue?

**Comment by oshihirii** [comment]
https://xkcd.com/979/

![wisdom_of_the_ancients](https://github.com/user-attachments/assets/179b71af-b769-4c66-adc3-5b6f8b6348a7)
