### ISSUE TITLE
Connect to mongos via TLS/SSL

### ISSUE THREAD

**Issue by Stellaverse** [kcbanner/connect-mongo#192]
Hi folks,

I use `connect-mongo` as the storage module for `express-sessions`, and all was working well until I switched to the new `'MongoDB+' TLS/SSL` deployment from `Compose.io`, and now I can't connect.

I don't know their architecture in detail, but I do know they use `mongos` instances as front-ends for the database servers themselves.

More information can be found here:
https://www.compose.io/articles/bringing-ssl-and-more-to-compose-mongodb/
And here:
https://www.compose.io/articles/going-ssl-with-compose-mongodb-plus/
And here:
https://www.compose.io/articles/one-missing-key-and-how-it-broke-node-js-and-mongodb/

So when you connect you need to declare `mongos` options and your connection code ends up looking like so:

```
var ca = [fs.readFileSync('./Mongo-Key.pem')];
	
	var url = 'mongodb://MY_MONGO_USER:MY_MONGO_PASS@mongos1.compose.io:12345,mongos2.compose.io:54321/Sessions';
	
	app.use(session({
		key : 'SessionKey',
		secret : 'CATONTHEKEYBOARD',
		cookie : {
			path : '/',
			httpOnly : true,
			maxAge : null
		},
		store : new MongoStore({
			url : url,
			mongoOptions : {
				mongos : {
					ssl : true,
					sslValidate : true,
					sslCA : ca,
					ca : ca, 
					poolSize : 1,
					reconnectTries : 1
				}
			},
			collection : 'sessions',
			stringify : false
		}, function(result) {

			console.log('Connected to sessions db!');
			return callback();

		})
	}));
```

That connection string, along with those connection options, works using the `mongo-native` driver. I can connect and perform all operations.

But applying them in this context produces ... nothing. It just hangs.

Is this type of connection supported?
Any suggestions about how to go about getting *any* output from my app. Errors or warnings or really anything at this point.
Is there a different configuration I should be declaring?

Thanks for any help!

**Comment by jdesboeufs** [comment]
Hi,

You can enable the debug mode prefixing the node command with `DEBUG=connect-mongo`.

There is one big problem in your code: the callback has no chance to be called!
The second argument of MongoStore creation has been dropped since `v0.5.0`.

But you can emulate an equivalent behavior like that:
```js
(new MongoStore({ ... })).on('connected', function () {});
```

Current versions of `connect-mongo` are able to manage their connection state internally, so this callback is completely optional today.

Hope it helps.

**Comment by Stellaverse** [comment]
Bingo. That did the trick. Thanks @jdesboeufs!

**Comment by sushilnagpal** [comment]
Hi,

Auto-reconnect doesn't work if MongoStore connect to mongod via TLS/SSL. Any idea?

**Comment by jdesboeufs** [comment]
On which connection strategy?

**Comment by sushilnagpal** [comment]
Here is my code - 

    app.use(session({
        secret: 'angular-fullstack secret',
        store: new mongoStore({
            url: config.mongo.uri,
            collection: 'sessions',
            server: config.mongo.options.server,
            username: config.mongo.options.user,
            password: config.mongo.options.pass,
            auto_reconnect:true
        }, function () {
            console.log('db connection open');
        })
    }));


Config.js - 

     mongo: {
          uri: 'mongodb://localhost/fullstack-dev',
          options: {
               db: {
                   safe: true
               },
               server: {
                    auto_reconnect: true,
                    sslValidate: false,
                    ssl: true,
                    sslCert: cert,
                    socketOptions: { keepAlive: 1 }
              },
              user: '',
              pass: ''
          }
    }

**Comment by jdesboeufs** [comment]
Connection options must be passed into `mongoOptions` key.
`server`, `username`, `password` and `auto_reconnect` aren't valid options for constructor.

**Comment by jdesboeufs** [comment]
And above all, the connection callback in the constructor doesn't exist anymore (since `0.5.0`).

**Comment by sushilnagpal** [comment]
Thanks @jdesboeufs for your valuable time.. I was using 0.4.1 release. I upgraded connect-mongo in my application from 0.4.1 to 0.8.2 and even after upgrading and following examples available at https://github.com/kcbanner/connect-mongo, my application is unable to auto reconnect with MongoDB using SSL. I think it is an issue with mongoose as well because mongoose also behaving same. Although if I start mongod service without SSL, my application is able to reconnect with mongo is network connection lost or mongod service restarted. There is no example available at https://github.com/kcbanner/connect-mongo for connecting mongo db using SSL.

**Comment by jdesboeufs** [comment]
All connection options available can be found here: https://mongodb.github.io/node-mongodb-native/driver-articles/mongoclient.html
Content of `mongoOptions` will be passed to the MongoClient constructor.

**Comment by sushilnagpal** [comment]
Thanks @jdesboeufs  appreciate your help! I was using old versions of mongoose and connect-mongo. Upgrading to latest versions of both resolved my issue. Definitely after making changes in constructor as well:
Working code:

    app.use(session({
        secret: 'angular-fullstack secret',
        store: new mongoStore({
            db: mongoose.connection.db,
            collection: 'sessions',
            autoReconnect:true,
            autoRemove: 'interval',
            autoRemoveInterval: 10
        })
    }));
