### ISSUE TITLE
Ignore requets from HAProxy

### ISSUE THREAD

**Issue by rodmoreno** [kcbanner/connect-mongo#193]
I am developing an application using Kraken.js and to manage the sessions I decided to use: connect-mongo.

I have a setup like this:

    module.exports = function SessionLib(opts) {
      return session({
        secret: opts.secret,
        resave: opts.resave,
        saveUninitialized: opts.saveUninitialized,
        store: new MongoStore({
          url: opts.url,
          ttl: opts.ttl
        })
      });
    };

The deployment the app in OpenShift with the option of auto-scaling, OpenShift are using HAProxy for auto scaling but this is causing me an error generating too many sessions in my MongoDB (About 250,000 in last weekend).

There is the possibility of not keeping HAProxy sessions?

**Comment by behcet-li** [comment]
Does your reverse proxy detect health of the application servers by pinging it on timed intervals ?

**Comment by franckl** [comment]
I had the same issue with openshift.
Here is what I did to detect the proxy 
```javascript
if (production) {
                    if (req.ips.length === 0 || req.headers['user-agent'] === 'Ruby') {
                        req.session.destroy(function () {});
                    } else {
                        req.session.ips = req.ips;
                        req.session.useragent = req.headers['user-agent'];
                    }
                    next();
                }
```

**Comment by jdesboeufs** [comment]
Can i close?
