### ISSUE TITLE
Failing when using Node 4.0.0

### ISSUE THREAD

**Issue by juancarloscancela** [kcbanner/connect-mongo#194]
Hi!

Seems that library is not working with Node v4.0.0.

I've just run npm install, and got this error:

> kerberos@0.0.14 install /home/bak/Documents/n4/mongo/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/home/bak/Documents/n4/mongo/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
../lib/kerberosgss.c:27:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic push
 ^
../lib/kerberosgss.c:28:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic ignored "-Wdeprecated-declarations"
 ^
../lib/kerberosgss.c: In function ‘authenticate_gss_client_wrap’:
../lib/kerberosgss.c:348:19: warning: variable ‘server_conf_flags’ set but not used [-Wunused-but-set-variable]
   char buf[4096], server_conf_flags;
                   ^
../lib/kerberosgss.c: At top level:
../lib/kerberosgss.c:687:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic pop
 ^
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
/usr/bin/ld: cannot find -lkrb5
/usr/bin/ld: cannot find -lgssapi_krb5
collect2: error: ld returned 1 exit status
kerberos.target.mk:133: recipe for target 'Release/obj.target/kerberos.node' failed
make: *** [Release/obj.target/kerberos.node] Error 1
make: Leaving directory '/home/bak/Documents/n4/mongo/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-28-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/bak/Documents/n4/mongo/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 

Any ideas?
Thanks in advance.

**Comment by juancarloscancela** [comment]
Just an update: Issue reproducible also with Node 4.1.0

**Comment by jdesboeufs** [comment]
`kerberos` in an optional dependency.
`connect-mongo` -> `mongodb` -> `mongodb-core` -> `kerberos`.

The problem is not related to `connect-mongo`. Are you sure the installation failed?
Maybe it's just a warning.

**Comment by riston** [comment]
With Node v4.1.0 the installation seems throwing the only warning.

**Comment by zackiles** [comment]
@juancarloscancela This is coming from the mongodb package, not this repo. A recent update to the mongodb driver (or node-gyp) shows this error during node-gyp bindings, but it is only a warning and you can ignore it. If you'd like to be able to support Kerbero s(or just stop this warning) you can install the missing kerbeos library with `apt-get install libkrb5-dev.`. Then remove and reinstall npm mongodb and this warning will be gone.

**Comment by csotiriou** [comment]
Indeed, ```apt-get install libkrb5-dev``` fixed the problem for me. Thanks.

**Comment by winnemucca** [comment]
Is there more to this command?  I am getting apt-get command not found

**Comment by behcet-li** [comment]
@winnemucca [aptitude](https://en.wikipedia.org/wiki/Aptitude_%28software%29) is a package manager specific to Debian systems. You need to install ``libkrb5-dev`` software preferably with something specific to your OS

**Comment by taoli-paypal** [comment]
Could anyone share some method to fix it on Mac OSx. Not able to find it with hombrew. Besides, seems mongoose still working without this ?

**Comment by coty-crg** [comment]
taoli-paypal is right, I cannot get this on osx either

**Comment by caoyang1024** [comment]
what if just ignore it? any problem in future?

**Comment by kbariotis** [comment]
I've found this, haven't tested yet: http://stackoverflow.com/a/33140170/1955940
