### ISSUE TITLE
res.redirect happening before req.flash

### ISSUE THREAD

**Issue by franckl** [kcbanner/connect-mongo#195]
Hi Jerome,

It seems connect-mongo is causing the issue referenced below :
https://github.com/jaredhanson/connect-flash/issues/23#issuecomment-141786424

What do you think ?

**Comment by behcet-li** [comment]
It's a race condition. User gets redirected to new page before session gets saved on database.

Try executing a ``req.session.save(callback)`` before flash and wait for save callback to redirect to user.

**Comment by behcet-li** [comment]
@franckl Any updates ?

**Comment by jontelm** [comment]
https://github.com/expressjs/session/pull/157 https://github.com/mweibel/connect-session-sequelize/issues/20 https://github.com/jaredhanson/connect-flash/issues/23

**Comment by jdesboeufs** [comment]
Ok it's not related to `connect-mongo`.
`connect-flash` should be fixed to ensure session has been saved (whatever the session store used).

**Comment by malcolmocean** [comment]
For people who come across this in future searching...

I was halfway through rolling my own new version of `req.flash`, when I was looking through [the docs of `express-session`](https://github.com/expressjs/session) and came across this gem:
> Note Since version 1.5.0, the cookie-parser middleware no longer needs to be used for this module to work. This module now directly reads and writes cookies on req/res. Using cookie-parser may result in issues if the secret is not the same between this module and cookie-parser.

And lo, I had these lines:

```javascript
app.use(require('cookie-parser')())
const session = require('express-session')
const MongoStore = require('connect-mongo')(session)
app.use(session({
  secret: process.env.SESSION_STORE_SECRET,
  store: new MongoStore({mongooseConnection: mongoose.connection}),
  maxAge: 10*365*24*60*60*1000, // set to 10 years
  resave: false,
  saveUninitialized: false
}))
```

Once I changed the `cookie-parser` line to:
```javascript
app.use(require('cookie-parser')(process.env.SESSION_STORE_SECRET))`
```
it worked exactly as expected!

(For some people, the answer will be to remove `cookie-parser` altogether.)
