### ISSUE TITLE
lodash dependency not strict enough

### ISSUE THREAD

**Issue by vdust** [kcbanner/connect-mongo#206]
In package.json, the lodash dependency is set to "*".

Upon installing a project that depends on connect-mongo, i ran into a missing symbol issue ( _.assign is not a function ). The issue ended up being caused by lodash 0.9.2 that was installed as the top-level version (and satisfied the loose dependency)... But this version doesn't have lodash.assign. Forcing a dependency on lodash^3.0.0 in this other project fixed the issue, but since it doesn't use it directly, i should not have to do that.

lodash dependency should be set to at least ">=3.0.0" (older versions are deprecated and no longer maintained so there is no reason to accept them as dependencies in new releases).

**Comment by vdust** [comment]
I just noticed that this issue would be fixed by merging the pull request #204.

**Comment by jdesboeufs** [comment]
Fixed in `1.0.0`.
