### ISSUE TITLE
package.json points to wrong entry point

### ISSUE THREAD

**Issue by nulliel** [kcbanner/connect-mongo#208]
The entry point of version 1.0.0 is ./lib which is invalid and causes node to crash.
Changing it to ./src fixes the issue.

**Comment by gkoberger** [comment]
This took my site down when I deployed.

**Comment by jdesboeufs** [comment]
Oops!
I go home and I fix that...
Le jeu. 17 déc. 2015 à 19:43, Gregory Koberger <notifications@github.com> a
écrit :

**Comment by nulliel** [comment]
Fixed in 1.0.1
