### ISSUE TITLE
use of const in strict mode

### ISSUE THREAD

**Issue by mosquito1994** [kcbanner/connect-mongo#209]
I'm sorry, I'm new in node. I've got a problem said 'use of const in strict mode' with connect-mongo when trying to support connect-flash.I check my code according to your readme guidance but it doesn't work.How can I solve the problem please?

**Comment by jdesboeufs** [comment]
What is your node version?
If it's under 4.0 you must use `require('connect-mongo/es5')`.
Le ven. 18 déc. 2015 à 04:26, mosquito1994 <notifications@github.com> a
écrit :

**Comment by kostysh** [comment]
require('connect-mongo/es5') not works because of 
Error: Cannot find module 'connect-mongo/es5'

**Comment by jdesboeufs** [comment]
OK. Working on it!

**Comment by kostysh** [comment]
Ok, after npm update
require('connect-mongo/es5') working fine

Good to be documented on npm page, thanks

**Comment by jdesboeufs** [comment]
I added a test to check ES5 version loading.
Also updated the way we deal with those versions + published 1.0.2.

**Comment by cleechtech** [comment]
Make sure your package.json reads `"connect-mongo": "1.0.0"` in "dependencies". Also your require statement must look like: `require('connect-mongo/es5')`

The newest version of connect-mongo uses a different version of javascript called ES6.

**Comment by rogercastaneda** [comment]
I've the same problem
I tried the following code
var express = require('express');
var expressSession = require('express-session');

var mongoStore = require('connect-mongo')(expressSession);
var sessionStore = new MongoStore({
    host: '127.0.0.1',
    port: '27017',
    db: 'session',
});

but i get the following error:

/Users/alf/node_modules/connect-mongo/src/index.js:3
const Promise = require('bluebird');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/roger/node_modules/connect-mongo/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by jdesboeufs** [comment]
@rogercastaneda You must use the ES5 version, and use a connection string.

**Comment by ducito** [comment]
`require('connect-mongo/es5')`
Thanks. It's work for me.

**Comment by rogercastaneda** [comment]
Thanks, it was my fault, i was using MongoStore instead of mongoStore. It works now :)
