### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by hainzee** [kcbanner/connect-mongo#212]
I get a couple of build errors on installation. I have Windows SDK 7.1, MongoDB 3.0 and Visual Studio 2015 already installed. Is there a compatibility issue?

Shell log:

> kerberos@0.0.3 install C:\projects\app\node_modules\connect-mongo\node_
modules\mongodb\node_modules\kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\projects\app\node_modules\connect-mongo\node_modules\mongodb\node_modu
les\kerberos>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\no
dejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp
.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the regi
stry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versi
on number. [C:\projects\app\node_modules\connect-mongo\node_modules\mong
odb\node_modules\kerberos\build\kerberos.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the
 file specified. [C:\projects\app\node_modules\connect-mongo\node_module
s\mongodb\node_modules\kerberos\build\kerberos.vcxproj]

> bson@0.2.5 install C:\projects\app\node_modules\connect-mongo\node_modu
les\mongodb\node_modules\bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\projects\app\node_modules\connect-mongo\node_modules\mongodb\node_modu
les\bson>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs
\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
 rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the regi
stry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versi
on number. [C:\projects\app\node_modules\connect-mongo\node_modules\mong
odb\node_modules\bson\build\bson.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the
 file specified. [C:\projects\app\node_modules\connect-mongo\node_module
s\mongodb\node_modules\bson\build\bson.vcxproj]

connect-mongo@0.4.1 node_modules\connect-mongo
└── mongodb@1.3.23 (kerberos@0.0.3, bson@0.2.5)

**Comment by jdesboeufs** [comment]
No compatibility issue!
It's just a `mongodb` optional dependency which fail to build...

As it's not directly related to `connect-mongo`, if you want (and you should) to improve that output, please warn `mongodb` package maintainers.
