### ISSUE TITLE
Bluebird warning

### ISSUE THREAD

**Issue by vedi** [kcbanner/connect-mongo#214]
```
    "connect-mongo": "^1.1.0",
    "bluebird": "^3.3.1",
```

After every request I see in my log stacktrace including:

```
Warning: a promise was created in a handler but was not returned from it
    at MongoStore.set (./node_modules/connect-mongo/src/index.js:240:18)
    at Session.save (./node_modules/express-session/session/session.js:71:25)
    at Session.save (./node_modules/express-session/index.js:331:15)
```

I think it's better to fix it on connect-mongo level.

Thanks.

**Comment by jdesboeufs** [comment]
Any idea?

**Comment by jaecSolutions** [comment]
Same promblem !

**Comment by zbigg** [comment]
Same problem. Quick analysis doesn't reveal any obvious bug in `connect-mongo` it may be bluebird issue.

Workaround, to disable this warning:

    require('bluebird').config( { warnings: { wForgottenReturn: false } } );

**Comment by chovy** [comment]
I'm still getting this.

**Comment by Awk34** [comment]
I believe this is also because of express-session: https://github.com/expressjs/session/blob/master/index.js#L332

There's nothing more to do with this module
