### ISSUE TITLE
Session creation hook

### ISSUE THREAD

**Issue by james-s-turner** [kcbanner/connect-mongo#215]
Hi,
I'd like to be able to log whenever a session is created. I initially thought I could simply provide a function for `transformId` that writes to my log file and returns the sessionId unchanged. However it is called multiple times with the same sessionId. Is it possible to find out when a new session is created.

Thanks

**Comment by jdesboeufs** [comment]
Hi,
The `MongoStore` emits some events: at least `set`, `touch`, `destroy`. It's more appropriate than your workaround ;)
But it could be useful to know when a session ID is persisted for the first time.
The `rawResponse` returned by the `upsert` may help in this case. We must investigate.

**Comment by jdesboeufs** [comment]
@james-s-turner Session creation hook has been added.
