### ISSUE TITLE
Session expiry event

### ISSUE THREAD

**Issue by gsikorski** [kcbanner/connect-mongo#217]
I want to make some cleanup in my database in two condititons:
1. User logs out
2. Session expires

I could use `destroy` event in the first case, but there seems to be no way to trigger any action on expiry. I tried both `autoRemove` settings (`native` and `interval`). They both seem to work (the session is actually cleaned up from the Mongo database), however my `destoy` event is not called. Is this possible at all?

**Comment by daviwil2** [comment]
Hi gsikorski. I have a similar need. connect-mongo doesn't spontaneously emit an event when a session expires; the get(sid, callback) function in the public API is called to check the session validity. I've modified it as below (the else statement and this.emit('expired', sid) code) to emit that event when a session is checked and found to be expired.

.then(session => {
  if (session) {
    var s = this.transformFunctions.unserialize(session.session);
    if(this.options.touchAfter > 0 && session.lastModified){
      s.lastModified = session.lastModified;
    }
    this.emit('touch', sid);
    return s;
  } else {
    this.emit('expired', sid);
  }
})

But as I say this isn't generated spontaneously when a session expires.  Maybe use a setInterval function to periodically check the session (calling the get API) which in the modified code above would then trigger the event? Or query the table in the database for the user as, as soon as the session expires, it's removed from the collection (assuming the default of autoRemove: 'native'). Or see if Mongoose middleware (if you're using Mongoose...) or the connect-mongo code can be modified further to emit an event when it cleans the database. I'm looking into the latter, when and if I find a solution I'll post it here.

**Comment by daviwil2** [comment]
OK so to clean the database using 'native' autoRemove connect-mongo uses MongoDB's TTL function.  See https://docs.mongodb.org/manual/tutorial/expire-data/. And it doesn't fire a callback or emit and event or anything when it does it.  So to trap the removal event you need to not use autoRemove: native but instead use the interval option and then modify the setAutoRemoveAsync() function's setInterval timer to query for any matching documents, fire events, and then clean the matching docs. Ugh.

**Comment by gsikorski** [comment]
Yeah, I have already looked through it and found a better design to my application to work around the issue. Actually what am I doing is checking if the session still exists when I need to do something with my data other. That solved my problem without need to generate event in some custom way. It's a shame though `connect-mongo` does not support it...

**Comment by jdesboeufs** [comment]
`autoRemove: false`.
Then you can define your own cleanup tasks.
You just have to query the session collection with `{ expires: { $lt: new Date() } }`.

If you find an elegant and efficient way to collect expiring session ids, I'll be happy to accept your PR.
