### ISSUE TITLE
node-mongodb driver compatability

### ISSUE THREAD

**Issue by jamesongithub** [kcbanner/connect-mongo#218]
According to the README.md MongoDB is supported up to 3.2, but the native mongodb driver is supported up to 2.0 only. 

Here it says you need to have the 2.1 driver to use with mongodb 3.2:
https://docs.mongodb.org/ecosystem/drivers/driver-compatibility-reference/#reference-compatibility-mongodb-node

So does connect-mongo support the 2.1.x node-mongodb driver?

**Comment by jdesboeufs** [comment]
Yes of course. I've updated the README.md.

**Comment by jamesongithub** [comment]
Thanks!
