### ISSUE TITLE
Accept a Promise for a mongo DB instance?

### ISSUE THREAD

**Issue by nickb1080** [kcbanner/connect-mongo#221]
Would you be open to a PR that would accept a promise that resolves to a mongo DB instance? The implementation would probably look something like the following in the constructor:
```js
// ...
} else if (options.dbPromise) {
  dbPromise
    .then(db => this.handleNewConnectionAsync(db))
    .catch(err => this.connectionFailed(err))
}  // ...
```

**Comment by jdesboeufs** [comment]
Yes!

**Comment by Redsandro** [comment]
This would be very much appreciated. In `node-mongodb-native` 2+ you connect without using a `db` instance and only have access to the db in a callback. So accepting a promise for the db would prevent us from having to beat around the bush. :+1:
