### ISSUE TITLE
Using connect-mongo with db instance created via createConnection method

### ISSUE THREAD

**Issue by kutsokon** [kcbanner/connect-mongo#225]
I'm using mongoose method "connect" to create instance of my db and defining MongoStore option "db" as db.connection.db. Yes, we are using old version of connect-mongo). So, now I need to connect additional db to my application, it can be possible only via another method of mongoose - "createConnection". I've replaced methods and now my sessions dont work. First of all there was error: Trying to open unclosed connection, after that I've been making any changes: updating version of connect-mongo, passing different options to new MongoStore store, url, db etc. but its not working, sometimes without errors.  We are also using "passport" for identification. Did anybody have such trouble? I think the main problem in different approach in "createConnection" than in "connect" but I'm not shure. Thanks for answers.

**Comment by kutsokon** [comment]
I've resolved this issue, createConnection returns another instance, so you need to manage it differently.

**Comment by srajbr** [comment]
Hello @kutsokon can you share how you managed to convert the instance to desired type for MongoStore

**Comment by kutsokon** [comment]
```
app.use(session({
		store: new mongoStore({
			mongooseConnection: db
		})
	}));
```
db is a mongoose instance

**Comment by srajbr** [comment]
Thanks @kutsokon :)
