### ISSUE TITLE
Sessions collection is too big

### ISSUE THREAD

**Issue by zilions** [kcbanner/connect-mongo#226]
I installed `connect-session` 2 days ago now. Today I checked my sessions collection and found out that there were more than 200,000 documents in there! I tried deleting my collection and waiting 60 seconds, and there were already 200 documents in there.

Why are documents being resaved even though I have resave set to false? It seems as if documents are being saved endlessly...

Here is my current configuration:

```
app.use(session({
    secret: config.secret,
    resave: false,
    saveUninitialized: false,
    unset: 'destroy',
    store: new MongoStore({
        mongooseConnection: mongoose.connection,
        touchAfter: 3600, //Restore once every hour
        autoRemove: 'interval',
        autoRemoveInterval: 60 //Remove after one hour
    })
}));
```

At most I would only have around 3 users using my app at the moment.

**Comment by jdesboeufs** [comment]
`connect-mongo` just exposes some basic accessors to `express-session`.
If you have issues with `resave: false` you must investigate on the `express-session` side.

**Comment by romeboards** [comment]
@zilions also experiencing this issue, and I have `resave: true`

Any discoveries on the cause of this?

**Comment by bonesoul** [comment]
@zilions i'm also having a similar issue (https://github.com/expressjs/session/issues/413), you found a fix for this?
